#!/bin/sh

if [ -z "$1" ]; then
  echo "you need to pass an argument (text or URL)"
  exit 1
fi

MESSAGE_TEXT=$1

curl -s \
  --form-string "token=${PUSHOVER_APP_TOKEN}" \
  --form-string "user=${PUSHOVER_USER_KEY}" \
  --form-string "message=${MESSAGE_TEXT}" \
  --form-string "sound=bike" \
  https://api.pushover.net/1/messages.json

printf "\n"
